// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: messages/join_party_mn.proto

package messagesmn

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type JoinPartyLeaderCommMn_ResponseTypeMn int32

const (
	JoinPartyLeaderCommMn_Unknown        JoinPartyLeaderCommMn_ResponseTypeMn = 0
	JoinPartyLeaderCommMn_Success        JoinPartyLeaderCommMn_ResponseTypeMn = 1
	JoinPartyLeaderCommMn_Timeout        JoinPartyLeaderCommMn_ResponseTypeMn = 2
	JoinPartyLeaderCommMn_LeaderNotReady JoinPartyLeaderCommMn_ResponseTypeMn = 3
	JoinPartyLeaderCommMn_UnknownPeer    JoinPartyLeaderCommMn_ResponseTypeMn = 4
)

// Enum value maps for JoinPartyLeaderCommMn_ResponseTypeMn.
var (
	JoinPartyLeaderCommMn_ResponseTypeMn_name = map[int32]string{
		0: "Unknown",
		1: "Success",
		2: "Timeout",
		3: "LeaderNotReady",
		4: "UnknownPeer",
	}
	JoinPartyLeaderCommMn_ResponseTypeMn_value = map[string]int32{
		"Unknown":        0,
		"Success":        1,
		"Timeout":        2,
		"LeaderNotReady": 3,
		"UnknownPeer":    4,
	}
)

func (x JoinPartyLeaderCommMn_ResponseTypeMn) Enum() *JoinPartyLeaderCommMn_ResponseTypeMn {
	p := new(JoinPartyLeaderCommMn_ResponseTypeMn)
	*p = x
	return p
}

func (x JoinPartyLeaderCommMn_ResponseTypeMn) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinPartyLeaderCommMn_ResponseTypeMn) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_join_party_mn_proto_enumTypes[0].Descriptor()
}

func (JoinPartyLeaderCommMn_ResponseTypeMn) Type() protoreflect.EnumType {
	return &file_messages_join_party_mn_proto_enumTypes[0]
}

func (x JoinPartyLeaderCommMn_ResponseTypeMn) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinPartyLeaderCommMn_ResponseTypeMn.Descriptor instead.
func (JoinPartyLeaderCommMn_ResponseTypeMn) EnumDescriptor() ([]byte, []int) {
	return file_messages_join_party_mn_proto_rawDescGZIP(), []int{1, 0}
}

type JoinPartyRequestMn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"` // the unique hash id
}

func (x *JoinPartyRequestMn) Reset() {
	*x = JoinPartyRequestMn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_join_party_mn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinPartyRequestMn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPartyRequestMn) ProtoMessage() {}

func (x *JoinPartyRequestMn) ProtoReflect() protoreflect.Message {
	mi := &file_messages_join_party_mn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPartyRequestMn.ProtoReflect.Descriptor instead.
func (*JoinPartyRequestMn) Descriptor() ([]byte, []int) {
	return file_messages_join_party_mn_proto_rawDescGZIP(), []int{0}
}

func (x *JoinPartyRequestMn) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type JoinPartyLeaderCommMn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string                               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`                                                         // unique hash id
	MsgType string                               `protobuf:"bytes,2,opt,name=MsgType,proto3" json:"MsgType,omitempty"`                                               // unique hash id
	Type    JoinPartyLeaderCommMn_ResponseTypeMn `protobuf:"varint,3,opt,name=type,proto3,enum=messages.JoinPartyLeaderCommMn_ResponseTypeMn" json:"type,omitempty"` // result
	PeerIDs []string                             `protobuf:"bytes,4,rep,name=PeerIDs,proto3" json:"PeerIDs,omitempty"`                                               // if Success , this will be the list of peers to form the ceremony, if fail , this will be the peers that are available
}

func (x *JoinPartyLeaderCommMn) Reset() {
	*x = JoinPartyLeaderCommMn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_join_party_mn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinPartyLeaderCommMn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPartyLeaderCommMn) ProtoMessage() {}

func (x *JoinPartyLeaderCommMn) ProtoReflect() protoreflect.Message {
	mi := &file_messages_join_party_mn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPartyLeaderCommMn.ProtoReflect.Descriptor instead.
func (*JoinPartyLeaderCommMn) Descriptor() ([]byte, []int) {
	return file_messages_join_party_mn_proto_rawDescGZIP(), []int{1}
}

func (x *JoinPartyLeaderCommMn) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *JoinPartyLeaderCommMn) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *JoinPartyLeaderCommMn) GetType() JoinPartyLeaderCommMn_ResponseTypeMn {
	if x != nil {
		return x.Type
	}
	return JoinPartyLeaderCommMn_Unknown
}

func (x *JoinPartyLeaderCommMn) GetPeerIDs() []string {
	if x != nil {
		return x.PeerIDs
	}
	return nil
}

var File_messages_join_party_mn_proto protoreflect.FileDescriptor

var file_messages_join_party_mn_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x22, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x50, 0x61, 0x72,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0xf5, 0x01, 0x0a, 0x13, 0x4a, 0x6f,
	0x69, 0x6e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50,
	0x65, 0x65, 0x72, 0x49, 0x44, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x50, 0x65,
	0x65, 0x72, 0x49, 0x44, 0x73, 0x22, 0x5a, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e,
	0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x03,
	0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x50, 0x65, 0x65, 0x72, 0x10,
	0x04, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x68, 0x6f, 0x72, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x73, 0x73, 0x2f, 0x67, 0x6f,
	0x2d, 0x74, 0x73, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_join_party_mn_proto_rawDescOnce sync.Once
	file_messages_join_party_mn_proto_rawDescData = file_messages_join_party_mn_proto_rawDesc
)

func file_messages_join_party_mn_proto_rawDescGZIP() []byte {
	file_messages_join_party_mn_proto_rawDescOnce.Do(func() {
		file_messages_join_party_mn_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_join_party_mn_proto_rawDescData)
	})
	return file_messages_join_party_mn_proto_rawDescData
}

var file_messages_join_party_mn_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_join_party_mn_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messages_join_party_mn_proto_goTypes = []interface{}{
	(JoinPartyLeaderCommMn_ResponseTypeMn)(0), // 0: messages.JoinPartyLeaderCommMn.ResponseTypeMn
	(*JoinPartyRequestMn)(nil),                // 1: messages.JoinPartyRequestMn
	(*JoinPartyLeaderCommMn)(nil),             // 2: messages.JoinPartyLeaderCommMn
}
var file_messages_join_party_mn_proto_depIdxs = []int32{
	0, // 0: messages.JoinPartyLeaderCommMn.type:type_name -> messages.JoinPartyLeaderCommMn.ResponseTypeMn
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_messages_join_party_mn_proto_init() }
func file_messages_join_party_mn_proto_init() {
	if File_messages_join_party_mn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_join_party_mn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinPartyRequestMn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_join_party_mn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinPartyLeaderCommMn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_join_party_mn_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_join_party_mn_proto_goTypes,
		DependencyIndexes: file_messages_join_party_mn_proto_depIdxs,
		EnumInfos:         file_messages_join_party_mn_proto_enumTypes,
		MessageInfos:      file_messages_join_party_mn_proto_msgTypes,
	}.Build()
	File_messages_join_party_mn_proto = out.File
	file_messages_join_party_mn_proto_rawDesc = nil
	file_messages_join_party_mn_proto_goTypes = nil
	file_messages_join_party_mn_proto_depIdxs = nil
}
